name: Laravel Release

on:
  push:
    branches:
      - master

jobs:
  release_production:
    name: Release web to production
    if: startsWith(github.event.head_commit.message, 'release-production:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy to production with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            eval "$(ssh-agent -s)"
            ssh-add .ssh/id_stocktree
            cd public_html/karisma
            git pull
            composer install
            php artisan migrate
            php artisan optimize:clear
            eval "$(ssh-agent -k)"
